<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Host.Plugin.Properties.xml" />

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <Description>Redis transport provider for SlimMessageBus</Description>
    <PackageTags>Redis transport provider SlimMessageBus MessageBus bus facade messaging client</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReleaseNotes />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlimMessageBus.Host\SlimMessageBus.Host.csproj" />
  </ItemGroup>

</Project>
