<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Host.Test.Properties.xml" />

  <ItemGroup>
    <ProjectReference Include="..\SlimMessageBus.Host.Test.Common\SlimMessageBus.Host.Test.Common.csproj" />
    <ProjectReference Include="..\..\SlimMessageBus.Host.GooglePubSub\SlimMessageBus.Host.GooglePubSub.csproj" />
    <ProjectReference Include="..\..\SlimMessageBus.Host\SlimMessageBus.Host.csproj" />
    <ProjectReference Include="..\..\SlimMessageBus.Host.Serialization.SystemTextJson\SlimMessageBus.Host.Serialization.SystemTextJson.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PubSub" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
