<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Host.Plugin.Properties.xml" />

  <PropertyGroup>
    <Description>Google Cloud Pub/Sub provider for SlimMessageBus</Description>
    <PackageTags>Google Cloud Pub/Sub GCP provider SlimMessageBus MessageBus messaging client</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="3.36.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlimMessageBus.Host\SlimMessageBus.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SlimMessageBus.Host.GooglePubSub.Test" />
  </ItemGroup>

</Project>
