<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Host.Plugin.Properties.xml" />

  <PropertyGroup>
    <Description>Common SQL logic for SlimMessageBus</Description>
    <PackageTags>SlimMessageBus SQL Common logic</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReleaseNotes />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlimMessageBus.Host\SlimMessageBus.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" Condition="'$(TargetFramework)' == 'net10.0' Or '$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>

</Project>
